name: Release package on Github

on:
  workflow_dispatch:

env:
  NODE_VERSION: 18.x

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@latest
        if: startsWith(github.ref, 'refs/tags/')       
        with:
          name: latest
          files: |
            dist
            FuncAlertToTeams
            host.json
